name: Update Readme

on:
  schedule: # Run workflow automatically
    - cron: '30 5 * * *' # Runs every morning at 05:30 am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts, YouTube videos, and GitHub activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://fihlon.swiss/en/post/index.xml"
          max_post_count: 5
          comment_tag_name: PERSONALBLOG
          commit_message: Updating latest personal blog posts
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://keep-on-rolling.ch/feed.xml"
          max_post_count: 5
          comment_tag_name: CYCLINGBLOG
          commit_message: Updating latest cycling blog posts
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVPiWk3TEQtNnuRFmYnafyw"
          max_post_count: 5
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "yyyy-mm-dd"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          comment_tag_name: YOUTUBE
          commit_message: Updating latest YouTube videos
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updating recent GitHub activity'