name: YouTube workflow

on:
  schedule: # Run workflow automatically
    - cron: '10 5 * * *' # Runs every morning at 05:10 am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest YouTube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVPiWk3TEQtNnuRFmYnafyw"
          max_post_count: 5
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          comment_tag_name: YOUTUBE
          commit_message: Updated with the latest videos